# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{toto-bongo}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Daniel Palacio"]
  s.date = %q{2011-05-10}
  s.description = %q{Minimal blog to use with your existing app}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/ext/ext.rb",
    "lib/toto-bongo.rb",
    "test/articles/1900-05-17-the-wonderful-wizard-of-oz.txt",
    "test/articles/2001-01-01-two-thousand-and-one.txt",
    "test/articles/2009-04-01-tilt-factor.txt",
    "test/articles/2009-12-04-some-random-article.txt",
    "test/articles/2009-12-11-the-dichotomy-of-design.txt",
    "test/autotest.rb",
    "test/templates/about.html.haml",
    "test/templates/archives.html.haml",
    "test/templates/article.html.haml",
    "test/templates/feed.builder",
    "test/templates/index.builder",
    "test/templates/index.html.haml",
    "test/templates/layout.html.haml",
    "test/test_helper.rb",
    "test/toto_test.rb",
    "toto-bongo-1.0.0.gem",
    "toto-bongo.gemspec"
  ]
  s.homepage = %q{https://github.com/danpal/toto-bongo}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Tiny blog for your existing app}
  s.test_files = [
    "test/autotest.rb",
    "test/test_helper.rb",
    "test/toto_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<riot>, [">= 0"])
      s.add_runtime_dependency(%q<builder>, [">= 0"])
      s.add_runtime_dependency(%q<rack>, [">= 0"])
      s.add_runtime_dependency(%q<RedCloth>, [">= 0"])
    else
      s.add_dependency(%q<riot>, [">= 0"])
      s.add_dependency(%q<builder>, [">= 0"])
      s.add_dependency(%q<rack>, [">= 0"])
      s.add_dependency(%q<RedCloth>, [">= 0"])
    end
  else
    s.add_dependency(%q<riot>, [">= 0"])
    s.add_dependency(%q<builder>, [">= 0"])
    s.add_dependency(%q<rack>, [">= 0"])
    s.add_dependency(%q<RedCloth>, [">= 0"])
  end
end

